version: "2.2"
services:
  #######################################
  # Web portal
  #######################################
  doc:
    image: "registry.gitlab.com/pages/hugo"
    command: hugo server --bind 0.0.0.0
    working_dir: /usr/share/blog
    volumes:
      - ${PWD}:/usr/share/blog
    ports:
      - "${PORT:-1313}:1313"
